### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by NapStabLuc** [tynidev/SpeedFlipTrainer#1]
Ok i do not know if you want to spend more time on this but i think it would be great to include optimal ranges for the flip angle and time to supersonic values. if its close to perfect make the massage green if its bad red and maybe close ones orange. i know c++ but am new to bakkesmod coding. :)

**Comment by smokeymaloy** [comment]
How do you get the plugin to work?

**Comment by tynidev** [comment]
Trying to get the bakkes plugin moderators to review my latest code. You can download this and install it manually for now if you'd like. But the plugin moderators have informed me they would get to this today. Thanks! Also once you get it please try it out and let me know about the thresholds of the different meters.

**Comment by tynidev** [comment]
It's approved FYI you can download the new version from the plugin manager or the site now.
