### ISSUE TITLE
Not seeing all metrics

### ISSUE THREAD

**Issue by RyanMelena** [tynidev/SpeedFlipTrainer#2]
I'm seeing logs for dodge angle, clock angle, and time to supersonic but nothing for time to first jump or time to cancel as referenced on the [plugin description](https://bakkesplugins.com/plugins/view/286).  Am I missing something?

**Comment by gally90** [comment]
I am facing the same issue.... any input would be appreciated

**Comment by tynidev** [comment]
Trying to get the bakkes plugin moderators to review my latest code. You can download this and install it manually for now if you'd like. But the plugin moderators have informed me they would get to this today. Thanks! Also once you get it please try it out and let me know about the thresholds of the different meters.

**Comment by tynidev** [comment]
It's approved FYI you can download the new version from the plugin manager or the site now.
