### ISSUE TITLE
Zip-Download link is down

### ISSUE THREAD

**Issue by ghost** [tynidev/SpeedFlipTrainer#9]
the bakkesmod download doesnt work because the link to digitaloceanspaces ist not available.

Link: https://bp-prod.nyc3.digitaloceanspaces.com/uploads/4_3af4e39dddc7eb76e136f32052d7b3dfdaf152719074cef7cd01347c6a08a478.zip

No response or download possible

**Comment by skajan1** [comment]
nvm its for all bakkesmod plugins
